name: reference-media-player-kiosk
base: core20
version: '0.1'
summary: Provides mpv player and gstreamer basic function for video rendering
description: |
  Reference snap packaging to glu mpv player, gstreamer and ubuntu-frame together
  eventually offers ability to play videos on top of ubuntu-frame

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

layout:
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/samba:
    bind: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/samba
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/pulseaudio:
    bind: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/pulseaudio
  /usr/share:
    bind: $SNAP/usr/share
  /usr/local/share/fonts:
    bind: $SNAP/usr/share/fonts

environment:
  LC_ALL: C.UTF-8
  LD_LIBRARY_PATH: $SNAP/graphics/lib
  LIBGL_DRIVERS_PATH: $SNAP/graphics/dri
  LIBVA_DRIVERS_PATH: $SNAP/graphics/dri
  __EGL_VENDOR_LIBRARY_DIRS: $SNAP/graphics/glvnd/egl_vendor.d
  GST_PLUGIN_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/gstreamer-1.0
  GST_PLUGIN_SYSTEM_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/gstreamer-1.0
  GST_PLUGIN_SCANNER: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner
  # XDG config
  XDG_CACHE_HOME:  $SNAP_USER_COMMON/.cache
  XDG_CONFIG_HOME: $SNAP_USER_DATA/.config
  WINDOWING: wayland
  # Font config
  FONTCONFIG_PATH: ${SNAP}/etc/fonts/conf.d
  FONTCONFIG_FILE: ${SNAP}/etc/fonts/fonts.conf

plugs:
  opengl:
  wayland:
  audio-playback:
  alsa:
  graphics-core20:
    interface: content
    target: $SNAP/graphics
    default-provider: mesa-core20

apps:
  mpv:
    command-chain:
    - bin/wayland-launch
    command: usr/bin/mpv

  gst-play:
    command-chain:
    - bin/wayland-launch
    command: usr/bin/gst-play-1.0


parts:
  mpv:
    plugin: nil
    stage-packages:
      - mpv

  gstreamer:
    plugin: nil
    stage-packages:
      - gstreamer1.0-tools
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-base-apps
      - gstreamer1.0-pulseaudio
      - gstreamer1.0-gl
      - freeglut3

  mesa:
    plugin: nil
    stage-packages:
      - libgl1-mesa-dri
      - libwayland-egl1-mesa
      - libglu1-mesa

  mir-kiosk-snap-launch:
    plugin: dump
    source: https://github.com/MirServer/mir-kiosk-snap-launch.git
    override-build:  $SNAPCRAFT_PART_BUILD/build-with-plugs.sh opengl wayland
    stage-packages:
      - inotify-tools

